# Matriks Invers

Matrik invers merupakan kebalikan dari suatu matriks, ketika matriks tersebut dikalikan dengan matriks inversnya akan menghasilkan matriks identitas. Matriks invers disimbolkan dengan $A^{-1}$. Matriks invers hanya berlaku pada matriks persegi yang memiliki jumlah baris dan kolom yang sama dan determinanya tidak nol.  
misal kita memiliki matriks A dan matriks inversnya $A^{-1}$, maka berlaku persamaan:
$A\times A^{-1}=A^{-1}\times A=I$
I merupakan matriks identitas.

## Sifat-sifat matriks  
JIka A mempunyai matrik invers, k bilangan bulat positif, dan c adalah skalar $\neq 0$ maka
1. $A^{-1}$ diinverskan menjadi $(A^{-1})^{-1}=A$
2. $A^{k}$ diinverskan menjadi $(A^{k})^{-1}=A^{k} A^{k} A^{k}=(A^{-1})^{k}=A^{-k}$
3. $cA$ diinverskan dan $(cA)^{-1}=\frac{1}{c}  A^{-1}, c\neq 0$
4. $A^{T}$ diinverskan dan $(A^{T})^{-1}=(A^{-1})^{T}$

## Penyelesaian sistem persamaan linier menggunakan matriks invers

Penyelesaian sistem persamaan linier menggunakan matriks invers melibatkan beberapa langkah. Misalkan Anda memiliki sistem persamaan linier dalam bentuk matriks \( Ax = b \), di mana \( A \) adalah matriks koefisien, \( x \) adalah vektor variabel, dan \( b \) adalah vektor hasil. Untuk menyelesaikan sistem ini menggunakan matriks invers, Anda dapat mengikuti langkah-langkah berikut:

1. Hitung determinan dari matriks koefisien \( A \). Jika determinan tidak nol, matriks \( A \) dapat diinvers.

2. Hitung matriks invers dari matriks koefisien \( A \), yaitu \( A^{-1} \).

3. Kalikan kedua sisi persamaan dengan invers dari matriks koefisien \( A \), sehingga Anda akan mendapatkan \( A^{-1}Ax = A^{-1}b \).

4. Karena \( A^{-1}A \) adalah matriks identitas, maka \( x = A^{-1}b \).

Berikut adalah contoh implementasi Python untuk menyelesaikan sistem persamaan linier menggunakan matriks invers:


Penyelesaian 4 persamaan linier menggunakan matrik invers.
$Ax=b\\
x=A^{-1}b
$

$$
\\1x_1+2x_2+x_3+1x_4=3\\
2x_1+4x_2+6x_3+x_4=12\\
2x_1+4x_2+8x_3+6x_4=20\\
4x_1+2x_2+6x_3+8x_4=20\\
$$

$$
\begin{equation*}
A=
\begin{bmatrix}
1&2&0&1\\
2&4&6&0\\
2&4&8&6\\
4&2&6&8\\
\end{bmatrix}
\end{equation*}
$$

$$
\begin{equation*}
x=
\begin{bmatrix}
x_1\\
x_2\\
x_3\\
x_4\\
\end{bmatrix}
\end{equation*}
$$

$$
\begin{equation*}
b=
\begin{bmatrix}
3\\
12\\
20\\
20\\
\end{bmatrix}
\end{equation*}
$$



In [1]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
import numpy as np
A =np.array([[1,2,0,1,1,0,0,0],[2,4,6,0,0,1,0,0],[2,4,8,6,0,0,1,0],[4,2,6,8,0,0,0,1]])
print(A)

[[1 2 0 1 1 0 0 0]
 [2 4 6 0 0 1 0 0]
 [2 4 8 6 0 0 1 0]
 [4 2 6 8 0 0 0 1]]


In [3]:
B = RowAdd(A, 0, 1, -2)
print(B)

[[ 1.  2.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  6. -2. -2.  1.  0.  0.]
 [ 2.  4.  8.  6.  0.  0.  1.  0.]
 [ 4.  2.  6.  8.  0.  0.  0.  1.]]


In [4]:
C = RowAdd(B, 0, 2, -2)
print(C)

[[ 1.  2.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  6. -2. -2.  1.  0.  0.]
 [ 0.  0.  8.  4. -2.  0.  1.  0.]
 [ 4.  2.  6.  8.  0.  0.  0.  1.]]


In [5]:
D = RowAdd(C, 0, 3, -4)
print(D)

[[ 1.  2.  0.  1.  1.  0.  0.  0.]
 [ 0.  0.  6. -2. -2.  1.  0.  0.]
 [ 0.  0.  8.  4. -2.  0.  1.  0.]
 [ 0. -6.  6.  4. -4.  0.  0.  1.]]


In [6]:
E = RowScale(D, 3, -1/6)
print(E)

[[ 1.          2.          0.          1.          1.          0.
   0.          0.        ]
 [ 0.          0.          6.         -2.         -2.          1.
   0.          0.        ]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [-0.          1.         -1.         -0.66666667  0.66666667 -0.
  -0.         -0.16666667]]


In [7]:
F = RowAdd(E, 3, 0, -2)
print(F)

[[ 1.          0.          2.          2.33333333 -0.33333333  0.
   0.          0.33333333]
 [ 0.          0.          6.         -2.         -2.          1.
   0.          0.        ]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [-0.          1.         -1.         -0.66666667  0.66666667 -0.
  -0.         -0.16666667]]


In [8]:
H = RowAdd(F, 3, 1, 1)
print(H)

[[ 1.          0.          2.          2.33333333 -0.33333333  0.
   0.          0.33333333]
 [ 0.          1.          5.         -2.66666667 -1.33333333  1.
   0.         -0.16666667]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [-0.          1.         -1.         -0.66666667  0.66666667 -0.
  -0.         -0.16666667]]


In [9]:
I = RowAdd(H, 1, 3, -1)
print(I)

[[ 1.          0.          2.          2.33333333 -0.33333333  0.
   0.          0.33333333]
 [ 0.          1.          5.         -2.66666667 -1.33333333  1.
   0.         -0.16666667]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [-0.          0.         -6.          2.          2.         -1.
  -0.          0.        ]]


In [10]:
J = RowScale(I, 3, -1/6)
print(J)

[[ 1.          0.          2.          2.33333333 -0.33333333  0.
   0.          0.33333333]
 [ 0.          1.          5.         -2.66666667 -1.33333333  1.
   0.         -0.16666667]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]]


In [11]:
K = RowAdd(J, 3, 0, -2)
print(K)

[[ 1.          0.          0.          3.          0.33333333 -0.33333333
   0.          0.33333333]
 [ 0.          1.          5.         -2.66666667 -1.33333333  1.
   0.         -0.16666667]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]]


In [12]:
L = RowAdd(K, 3, 1, -5)
print(L)

[[ 1.          0.          0.          3.          0.33333333 -0.33333333
   0.          0.33333333]
 [ 0.          1.          0.         -1.          0.33333333  0.16666667
   0.         -0.16666667]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]]


In [13]:
M = RowSwap(L, 3, 2,)
print(M)

[[ 1.          0.          0.          3.          0.33333333 -0.33333333
   0.          0.33333333]
 [ 0.          1.          0.         -1.          0.33333333  0.16666667
   0.         -0.16666667]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]
 [ 0.          0.          8.          4.         -2.          0.
   1.          0.        ]]


In [14]:
N = RowAdd(M, 3, 3, 1)
print(N)

[[ 1.          0.          0.          3.          0.33333333 -0.33333333
   0.          0.33333333]
 [ 0.          1.          0.         -1.          0.33333333  0.16666667
   0.         -0.16666667]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]
 [ 0.          0.         16.          8.         -4.          0.
   2.          0.        ]]


In [15]:
O = RowAdd(N, 2, 3, -16)
print(O)

[[ 1.          0.          0.          3.          0.33333333 -0.33333333
   0.          0.33333333]
 [ 0.          1.          0.         -1.          0.33333333  0.16666667
   0.         -0.16666667]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]
 [ 0.          0.          0.         13.33333333  1.33333333 -2.66666667
   2.          0.        ]]


In [16]:
P = RowScale(O, 3, 0.075 )
print(P)

[[ 1.          0.          0.          3.          0.33333333 -0.33333333
   0.          0.33333333]
 [ 0.          1.          0.         -1.          0.33333333  0.16666667
   0.         -0.16666667]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]
 [ 0.          0.          0.          1.          0.1        -0.2
   0.15        0.        ]]


In [17]:
Q = RowAdd(P, 3, 0, -3)
print(Q)

[[ 1.          0.          0.          0.          0.03333333  0.26666667
  -0.45        0.33333333]
 [ 0.          1.          0.         -1.          0.33333333  0.16666667
   0.         -0.16666667]
 [ 0.         -0.          1.         -0.33333333 -0.33333333  0.16666667
   0.         -0.        ]
 [ 0.          0.          0.          1.          0.1        -0.2
   0.15        0.        ]]


In [18]:
R = RowAdd(Q,3, 1, 1 )
print(R.round())

[[ 1.  0.  0.  0.  0.  0. -0.  0.]
 [ 0.  1.  0. -0.  0. -0.  0. -0.]
 [ 0. -0.  1. -0. -0.  0.  0. -0.]
 [ 0.  0.  0.  1.  0. -0.  0.  0.]]


In [19]:
H = np.array([[-1,0,0,1], [4,0.5,0,-2], [-4,0,1,2], [1,0,0,0]])
I = np.array([[3], [12], [20], [20]])
print(H@I)

[[ 17.]
 [-22.]
 [ 48.]
 [  3.]]


In [20]:
AI = np.array([[1, 0, 0, 1],[4, 0.5, 0, -2], [-4, 0, 1, 2], [1, 0, 0, 0]])
b = np.array([[3], [12], [20], [20]])
print("Ax = b")
print(f"Ax = {b}")

print("\n")
print("x = A^-1 b")
AI1 = AI @ b
print(f"x = {AI1}")

Ax = b
Ax = [[ 3]
 [12]
 [20]
 [20]]


x = A^-1 b
x = [[ 23.]
 [-22.]
 [ 48.]
 [  3.]]
