# Kofaktor Expansion

## **MENGHITUNG DETERMINAN MATRIX 4X4 DENGAN COFACTOR EXPANSION**         
$
A = \begin{bmatrix}
1 & 1 & 2 & 3 \\
1 & 2 & 1 & 1 \\
2 & 3 & 1 & 1 \\
2 & 1 & 2 & 1\\
\end{bmatrix}
$

disini saya akan mengambil baris ke 2                                  
$A21C21$                                  
$A22C22$                            
$A23C23$                         
$A24C24$                        
 

RUMUS COFACTOR ADALAH :                       
$ c_𝑖𝑗=(−1)^(𝑖+𝑗) 𝑑𝑒𝑡𝐴_𝑖𝑗 $ 


MAKA :                   
$C21$     =     $(-1)^2+^1 Det(M21)$                                
$C22$     =     $(-1)^2+^2 Det(M22)$                        
$C23$     =     $(-1)^2+^3 Det(M23)$                 
$C24$     =     $(-1)^2+^4 Det(M24)$                          

## 1. Mencari $DetM21$    
$                       
M21 = \begin{bmatrix}
1 & 2 & 3 \\
3 & 1 & 1 \\
1 & 2 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 

  A. mencari det(m21) dari matrix M21                               
      $
      M21C21 = \begin{bmatrix}
      2 & 3 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah -4                           
                                   
  B. mencari det(M22) dari matrix M21                               
      $
      M21C22 = \begin{bmatrix}
      1 & 3 \\
      1 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -2 
    
  C.  mencari det(M23) dari matrix M21                               
      $
      M21C22 = \begin{bmatrix}
      1 & 2 \\
      1 & 2\\                                                  
      \end{bmatrix}
      $
      determinannya M23 adalah 0

  jadi :                              
  C21   =  $3 * (-1)^2+^1 -4$   =     12                                            
  C22   =  $1 * (1)^2+^2 -2$  =     -2                                                     
  C23   =  $1 * (-1)^2+^3 0$  =     0                                   

  $DetM31$    = 12 + -2 + 0 = 10
  

  ## 2. Mencari $DetM22$    
$                       
M22 = \begin{bmatrix}
1 & 2 & 3 \\
2 & 1 & 1 \\
2 & 2 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 


  A. mencari det(m21) dari matrix M22                              
      $
      M32C21 = \begin{bmatrix}
      2 & 3 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah -4                           
                                   
  B. mencari det(m22) dari matrix M32                              
      $
      M32C22 = \begin{bmatrix}
      1 & 3 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -5

  C. mencari det(m23) dari matrix M22                               
      $
      M32C22 = \begin{bmatrix}
      1 & 2 \\
      2 & 2\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -2


  jadi :                              
  C21   =  $2 * (-1)^2+^1 -4$   =    8                                           
  C22   =  $1 * (1)^2+^2 -5$  =      -5                                                  
  C23   =  $1 * (-1)^2+^3 -2$  =     2                                  

  $DetM32$    = 8 + (-5) + 2 = 5


## 3. Mencari $DetM23$    
$                       
M23 = \begin{bmatrix}
1 & 1 & 3 \\
2 & 3 & 1 \\
2 & 1 & 1\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 

  A. mencari det(m21) dari matrix M23                              
      $
      M33C21 = \begin{bmatrix}
      1 & 3 \\
      1 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah - 2                           
                                   
  B. mencari det(m22) dari matrix M23                              
      $
      M33C22 = \begin{bmatrix}
      1 & 3 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -5

  C. mencari det(m23) dari matrix M23                               
      $
      M33C22 = \begin{bmatrix}
      1 & 1 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M23 adalah -1

  jadi :                              
  C21   =  $2 * (-1)^2+^1 -2$ =    4                                          
  C22   =  $3 * (1)^2+^2 -5$  =    -15                                                  
  C23   =  $1 * (-1)^2+^3 -1$  =    1                                  

  $DetM33$    = 4 + -15 + 1 = 10

## 4. Mencari $DetM24$    
$                       
M24 = \begin{bmatrix}
1 & 1 & 2 \\
2 & 3 & 1 \\
2 & 1 & 2\\
\end{bmatrix}
$                       

  C21   =  $(-1)^2+^1 Det(M21)$                                      
  C22   =  $(1)^2+^2 Det(M22)$                                         
  C23   =  $(-1)^2+^3 Det(M23)$ 

 A. mencari det(m21) dari matrix M24                             
      $
      M24C21 = \begin{bmatrix}
      1 & 2 \\
      1 & 2\\                                                  
      \end{bmatrix}
      $
      determinannya M21 adalah 0                        
                                   
  B. mencari det(m22) dari matrix M24                              
      $
      M24C22 = \begin{bmatrix}
      1 & 2 \\
      2 & 2\\                                                  
      \end{bmatrix}
      $
      determinannya M22 adalah -2

  C. mencari det(m23) dari matrix M24                              
      $
      M24C22 = \begin{bmatrix}
      1 & 1 \\
      2 & 1\\                                                  
      \end{bmatrix}
      $
      determinannya M23 adalah -1

  jadi :                              
  C21   =  $2 * (-1)^2+^1 0$ =    0                                         
  C22   =  $3 * (-1)^2+^2 -2$ =    -6                                                  
  C23   =  $1 * (-1)^2+^3 -1$  =    1                                 

  $DetM34$    = -6 + 1 = -5

# hitung determinan Matriks A
$C31$     =     $1*(-1)^2+^1 10$      =   -10                          
$C32$     =     $2*(-1)^2+^2 5$       =   10              
$C33$     =     $1*(-1)^2+^3 -10$      =   10          
$C34$     =     $1*(-1)^2+^4 -5$      =   -5   
dapat disimpulkan bahwa                                                                                              
$Det matriks A$    = -10 + 10 + 10 + -5 = 5                                
mari kita buktikan:

In [2]:
import numpy as np
A2 = np.array([[1,1,2,3], [1,2,1,1],[2,3,1,1],[2,1,2,1]])
print(A2)
print(np.linalg.det(A2).round())

[[1 1 2 3]
 [1 2 1 1]
 [2 3 1 1]
 [2 1 2 1]]
5.0
