# Detreminants

determianants adalah ukuran skalar dari sebuah matriks. Determinan dari matriks A umumnya dinyatakan dengan notasi det(A), det A, atau |A|. Determinan dapat dianggap sebagai faktor penskalaan transformasi yang digambarkan oleh matriks. Nilai determinan mencirikan beberapa sifat dari matriks tersebut, dan peta linier yang diwakili oleh           

## Sifat-sifat Determinan
1. Determinan dari suatu matriks identitas adalah 1 

In [1]:
import numpy as np
C = np.array([[1,0], [0,1]])
D = np.array([[1,0,0], [0,1,0], [0,0,1]])
print("Matriks C : \n", C)
print("Matriks D : \n", D)

Matriks C : 
 [[1 0]
 [0 1]]
Matriks D : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [2]:
E = np.linalg.det(C)
print(E)

1.0


2. Jika terdapat determinan C = determinan(AB)
= determinan(A).determinan(B)
= AA^1

In [3]:
A = np.array([[2,1], [3,0]])
B = np.linalg.inv(A)
A1 = np.linalg.det(A)
B1 = np.linalg.det(B)

print("determinan A : ", round(A1))
print("determinan B : ",round(B1))
C = A1*B1
print("det.A x det.B :",round(C))
print(A@B)

determinan A :  -3
determinan B :  0
det.A x det.B : 1
[[1. 0.]
 [0. 1.]]


3. Jika menukar baris pada suatu matriks, maka akan mengubah tanda determinasinya juga. misalnya pada matriks D sebagai acuan determinan sebelum ada perubahan baris.

In [4]:
import numpy as np
D = np.array([[1,4,2], [1,1,1],[3,2,1]])
E = np.linalg.det(D)
F = round(E)
print("determinan matriks D : ",F)

determinan matriks D :  5


In [5]:
D1 = np.array([[1,1,1], [1,4,2],[3,2,1]])
D2 = np.linalg.det(D1)
print("determinan matriks D :", round(D2))

determinan matriks D : -5


4. Jika menukar kolom pada suatu matriks, maka akan mengubah tanda dari determinan.

In [6]:
import numpy as np
D = np.array([[1,4,2], [1,1,1],[3,2,1]])
E = np.linalg.det(D)
F = round(E)
print("matriks D :\n", D)
print("determinan D :", F)
D1 = np.array([[4,1,2], [1,1,1],[2,3,1]])
E1 = np.linalg.det(D1)
F1 = round(E1)
print("matriks D1 :\n", D1)
print("determinan D1:", F1)

matriks D :
 [[1 4 2]
 [1 1 1]
 [3 2 1]]
determinan D : 5
matriks D1 :
 [[4 1 2]
 [1 1 1]
 [2 3 1]]
determinan D1: -5


5. Jika baris dari suatu matriks merupakan kelipatan dari baris lain maka determinanya 0. kelipatannya bisa 2 kali, 3 kali, dst.

In [7]:
import numpy as np
P = np.array([[1,4,2], [2,8,4], [3,2,1]])
print(np.linalg.det(P))

0.0


6. Jika kolom dari suatu matriks merupakan kelipatan dari kolom lain, maka determinan = 0.

In [8]:
import numpy as np
Q = np.array([[1,4,2], [2,8,3], [1,4,1]])
print(np.linalg.det(Q))

0.0


7. Determinan A = determinan A transpose, jumlah determinan suatu matriks A sama dengan determinan A transpose.

In [9]:
# det A = det A transpose
import numpy as np
A = np.array([[1,4,2], [1,1,1],[3,2,1]])
A_T = np.transpose(A)
B = np.linalg.det(A)
C = np.linalg.det(A_T)
print("determinan A : \n", round(B))
print("determinan A transpose :\n", round(C))

determinan A : 
 5
determinan A transpose :
 5


8. Matriks segitiga atas : jika dibawah diagonal utama [1,1,1] adalah 0, meskipun diatas diagonal utama tidak nol. Sedangkan Matriks segitiga bawah : jika diatas diagonal utama [1,1,1] adalah 0, meskipun dibawah diagonal utama tidak nol. jika melakukan operasi baris elementer tidak akan mengubah determinan matriks tersebut.

In [10]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [11]:
import numpy as np 
A = np.array([[1,4,2], [1,1,1],[3,2,1]])
print(A)
A1 = np.linalg.det(A)
print("determinan : ", round(A1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
determinan :  5


In [12]:
B = RowAdd(A, 0, 1, -1)
print(B)
B1 = np.linalg.det(B)
print("deteminan setelah ada OBE : ", round(B1))

[[ 1.  4.  2.]
 [ 0. -3. -1.]
 [ 3.  2.  1.]]
deteminan setelah ada OBE :  5


## Ekspansi Kofaktor 
Ekspansi kofaktor digunakan untuk mencari determinan dari suatu matriks dengan memanfaatkan kofaktor. Kofaktor merupakan suatu elemen dalam suatu matriks yang ditentukan oleh elemen minor tersebut yang diperoleh dengan menghilangkan baris dan kolom yang memuat elemen tersebut.
rumus kofaktor: $C_ij = (−1)^{(𝑖+𝑗)}. 𝑑𝑒𝑡(M_𝑖𝑗)$

In [13]:
import numpy as np
A = np.array([[1,3,2,4], [1,2,2,1], [3,1,1,2], [2,1,1,3]])
B = np.linalg.det(A)
print("Matriks A: \n", A)
print()
print("Determinan A : ", round(B))

Matriks A: 
 [[1 3 2 4]
 [1 2 2 1]
 [3 1 1 2]
 [2 1 1 3]]

Determinan A :  8
