# Eigenvalues dan Eigenvectors
$$Ax = \lambda x$$

$Ax$: vektor $x$ setelah transformasi linier

$\lambda x$: perkalian bilangan riel dari $x, i.e$. peregangan dari vektor $x$.
Transformasi linier untuk eigenvector menghasilkan peregangan vektor
sebanyak eigenvalue kali.




Misalkan $A$ adalah matrik bujur sangkar dengan derat $n$. JIka terdapat
vektor tidak nol $x$ dan skalar $\lambda$ sehingga
$Ax$ = $ \lambda x$
maka $\lambda$ disebut eigenvalue dari $A$, dan $x$ disebut eigenvector, yang nilainya
bersesuai dengan eigenvalue $\lambda$


**Contoh Menghitung Eigenvalue dan Eigenvactor Matriks 2x2**

**Contoh**  
  
Hitung eigen value dan eigen vector dari matrik A  
  

$
\begin{matrix}
    A = \begin{bmatrix}
        2 & 1 \\
        1 & 2 \\
    \end{bmatrix}
\end{matrix}
$


solusi:  


$
\begin{matrix}
    det(A - \lambda I) = \begin{bmatrix}
        2 - \lambda & 1 \\
        1 & 2 - \lambda \\
    \end{bmatrix}
    =
    (\lambda - 1) (\lambda - 3) = 0 
\end{matrix}
$


Untuk eigenvalue $\lambda_{1}$ = 1,


$
\begin{matrix}
    (A - \lambda_{1}I)x_{1}= \begin{bmatrix}
        1 & 1 \\
        1 & 1 \\
    \end{bmatrix}
    \begin{bmatrix}
        x_{1} \\
        x_{2} \\
    \end{bmatrix}
    \begin{bmatrix}
        0 \\
        0 \\
    \end{bmatrix}
    ,
    x_{1}
    =
    \begin{bmatrix}
        1 \\
        -1 \\
    \end{bmatrix}
\end{matrix}
$


Untuk eigenvalue $\lambda_{2}$ = 3,


$
\begin{matrix}
    (A - \lambda_{2}I)x_{2}= \begin{bmatrix}
        -1 & 1 \\
        1 & -1 \\
    \end{bmatrix}
    \begin{bmatrix}
        x_{1} \\
        x_{2} \\
    \end{bmatrix}
    \begin{bmatrix}
        0 \\
        0 \\
    \end{bmatrix}
    ,
    x_{2}
    =
    \begin{bmatrix}
        1 \\
        1 \\
    \end{bmatrix}
\end{matrix}
$

**Contoh Menghitung Eigenvalue dan Eigenvactor Menggunakan Numpy Matriks 2x2 dan 3x3**

In [1]:
#matriks 2x2
import numpy as np
from numpy.linalg import eig
A = np.array([[2,1],[1,2]])
w,v =eig(A)
print("E value",w)
print("E vector \n",v.round())

E value [3. 1.]
E vector 
 [[ 1. -1.]
 [ 1.  1.]]


In [7]:
#matriks 3x3
import numpy as np
from numpy.linalg import eig
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
w,v =eig(A)
print("E value",w)
print("E vector \n",v.round())

E value [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
E vector 
 [[-0. -1.  0.]
 [-1. -0. -1.]
 [-1.  1.  0.]]


**Contoh Implementasi Eigenvalue dan Eigenvector Implementasi PCA melalui EVD dengan python:**

In [1]:
import numpy as np

def pcaSVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)  # Pusatkan data

    u, sigma, vt = np.linalg.svd(X_centered, full_matrices=False)

    # Mengembalikan komponen utama dan eigenvalue
    return (X_centered @ vt.T), (sigma**2) / (n-1)

# Data contoh
x = np.array([[2, 1], [1, 2]])

komponen_utama, eigenvalue = pcaSVD(x)
print("Komponen utama:\n", komponen_utama.round())
print("Eigenvalue:\n", eigenvalue.round())


Komponen utama:
 [[-1. -0.]
 [ 1.  0.]]
Eigenvalue:
 [1. 0.]


  * Terdapat fungsi pcaEVD dengan parameter x.
  * n, p = X.shape untuk mendapatkan jumlah sampel dan jumlah fitur dari bentuk matriks x.
  * x _= x.mean(axis=0) untuk mengurangkan mean dari setiap kolom data sehingga data memiliki mean 0.
  * u, sigma, vt = np.linalg.svd(X, full_matrices=False) untuk memecah matriks x menjadi tiga matriks u, sigma dan vt.

  matriks u adalah matriks ortogonal yang kolom-kolomya adalah vektor singular kiri.

  matriks sigma adalah vektor yang berisi singular values.

  matriks vt adalah ortogonal yang baris-barisnya adalah vektor singular kanan.

  * return (X @ vt.T), (sigma**2) / (n-1) untuk mengembalikan nilai ke dalam fungsi.

  (X @ vt.T) adalah matriks hasil transformasi data asli ke ruang komponen utama.

  (sigma**2) / (n-1) adalah nilai eigen yang digunakan untuk menghitung proporsi variansi.