# Aljabar Matriks

## Matriks

## Pengertian Matriks
Matriks merupakan susunan bilangan real yang dapat diidentifikasi baris dan kolom nya yang ditempatkan didalam kurung siku, matriks dapat dinotasikan dengan huruf kapital seperti A,B, dan seterusnya. Didalam matriks terdapat elemen-elemen matriks yang dinotasikan dengan huruf kecil yang setiap elemen memiliki baris dan kolom yang berbeda, seperti $a_{ij}=$ a elemen, i baris, j kolom. contoh: $a_{12}$ artinya elemen a terletak dibaris 1 dan kolom ke 2.  

* Ukuran matriks ditentukan oleh jumlah baris dan kolom.  
contoh : Matriks A berukuran 3x3 (3 baris 3 kolom)
$
A=\begin{bmatrix}
2 & 4 & 5\\
4 & 6 & 9
\end{bmatrix}
$


### Jenis-jenis matriks:
1. Matriks nol, matriks yang semua elemen
penyusunnnya nol.
2. Matriks baris, matriks yang elemennya hanya satu baris.
3. Matriks kolom, matriks yang elemennya hanya satu kolom.
4. Matriks persegi adalah matriks yang mempunyai jumlah baris dan kolom yang sama.
5. Matriks diagonal,matriks persegi yang semua elemen di luar diagonal utamanya bernilai nol.
6. Matriks skalar, matriks yang elemen pada diagonal utamanya sama dan elemen diluar diagonal bernilai nol.
7. Matriks identitas, matriks skalar yang elemen pada diagonal utamanya sama dengan satu.
8. Matriks simetri, matriks persegi yang sama dengan transpose matriks itu sendiri.
9. Matriks simetri miring, matriks persegi yang sama dengan negatif matriks transposnya
10. Matriks segitiga atas, matriks persegi yang elemen-elemen di bawah diagonal utamanya adalah nol.
11. Matriks segitiga bawah, matriks persegi yang elem-elemen di atas diagonal utamanya adalah nol.
12. Matriks tranpose, matriks yang mengubah elemen di baris menjadi kolom. 

### Implementasi Matriks dengan Numpy  





In [1]:
import numpy as np
A = np.array([[1, 3],[2,1],[-3,0],[6,3]])
B = np.array([[3, 0, 4],[-1,-2,1],[4,6,2]])
C = np.array([[-2, 1],[-4,1]])
D = np.array([[2],[6]])

print("A=\n",A)
print("B=\n",B)
print("C=\n",C)
print("D=\n",D)
print("\n")
print("Ukuran matriks :",A.shape) #ukuran matriks
print("Jumlah baris :", A.shape[0])# jumlah baris
print("Jumlah kolom :", A.shape[1])# jumlah kolom

A=
 [[ 1  3]
 [ 2  1]
 [-3  0]
 [ 6  3]]
B=
 [[ 3  0  4]
 [-1 -2  1]
 [ 4  6  2]]
C=
 [[-2  1]
 [-4  1]]
D=
 [[2]
 [6]]


Ukuran matriks : (4, 2)
Jumlah baris : 4
Jumlah kolom : 2


Dengan metode *Shape* kita dapat mengakses ukuran matriks, berdasarkan jumlah baris dan kolom dalam array. Contoh: Matriks A memilki ukuran 3x3 dengan rincian 3 baris dan 3 kolom.

In [2]:
y = np.random.randint(5,size=(3,3)) # menampilkan angka random dengan rentang 0-5 dengan ukuran matriks 3x3
print(y)

[[2 4 3]
 [3 4 1]
 [1 3 1]]


## Operasi-operasi Matriks  


1. ***Perkalian Matriks***  
* Jika jumlah kolom dari matrik A sama dengan jumlah baris matrik B, maka matrik dapat dikalikan. Hasilnya adalah matrik AB, yang memiliki jumlah baris seperti jumlah baris matrik A dan kolom sejumlah kolom matrik B. $${(AB)_ij}$$ adalah kombinasi elemen baris i dari A dan kolom j dari B.




In [3]:
# Perkalian matriks c sebagai skalar
import numpy as np
A = np.array([[5,2,6],[1,7,2],[4,1,8]])
B = np.array([[1,5,2],[5,3,3],[5,9,3]])
c = 3
print('c(AB)\n',c*(A@B))
print('(cA)B\n',(c*A)@B)
print('A(cB)\n',A@(c*B))

c(AB)
 [[135 255 102]
 [138 132  87]
 [147 285 105]]
(cA)B
 [[135 255 102]
 [138 132  87]
 [147 285 105]]
A(cB)
 [[135 255 102]
 [138 132  87]
 [147 285 105]]


2. ***Matriks Transpose***  
matriks baru yang diperoleh dengan menukar baris dan kolom dari matriks aslinya.


In [4]:
import numpy as np
C = np.array([[3,4],[7,0],[6,9]])
C_T = C.transpose()
print('matrik C sebelum di transpose=\n', C)
print('matrik C setelah di transpose=\n',C_T)
print('ordo C_transpose adalah',C_T.shape)

matrik C sebelum di transpose=
 [[3 4]
 [7 0]
 [6 9]]
matrik C setelah di transpose=
 [[3 7 6]
 [4 0 9]]
ordo C_transpose adalah (2, 3)


### Program untuk mengalikan matriks

In [5]:
def perkalian(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Perkalian matriks tidak dapat dilakukan karena jumlah kolom dalam matriks pertama tidak sama dengan jumlah baris dalam matriks kedua")
        return None
    result = [[0 for _ in range(len(matrix2[0]))] for _ in range(len(matrix1))]
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j] += matrix1[i][k] * matrix2[k][j]
    return result

def tampilan_hasil(matrix):
    for baris in matrix:
        print(baris)

print ("Berikut adalah contoh matriks")
print ("""
matriks1=([[2,6,3],[1,2,5],[8,3,1]])
matriks2=([[3,1,5],[4,4,3],[9,7,5]])
""")
matriks1=([[2,6,3],[1,2,5],[8,3,1]])
matriks2=([[3,1,5],[4,4,3],[9,7,5]])
test = perkalian(matriks1, matriks2)
print("\nHasil perkalian matriks:")
tampilan_hasil(test)


Berikut adalah contoh matriks

matriks1=([[2,6,3],[1,2,5],[8,3,1]])
matriks2=([[3,1,5],[4,4,3],[9,7,5]])


Hasil perkalian matriks:
[57, 47, 43]
[56, 44, 36]
[45, 27, 54]
