# Algoritma PageRank

PageRank adalah algoritma yang dibuat oleh Larry Page. Algoritma ini digunakan oleh mesin pencarian Google yang memberikan bobot numerik untuk setiap elemen dari kumpulan dokumen hyperlink seperti Word Wide Web dengan tujuan untuk mengukur hubungan kepentingan dalam kumpulan dokumen tersebut. Dalam algoritma PageRank dihasilkan matriks yang menghitung probabilitas bahwa pengguna akan berpindah dari satu halaman ke halaman lainnya.

Algoritma PageRank umumnya diterapkan pada grafik berarah , namun dalam kasus grafik tidak berarah algoritma pagerank juga dapat digunakan dengan memodifikasi seperti yang diterapkan pada algoritma TextRank . Pada TextRank akan dibangun sebuah grafik yang berisi hubungan antar kalimat dalam dokumen. Simpul di dalam graf ini direpresentasikan sebagai satuan satuan yang akan diberikan peringkat. Vertex ini memiliki kemiripan yang dihubungkan oleh edge . Kemiripan disini dapat ditentukan dengan cosine kesamaan di mana akan didapat kesamaan dari setiap kalimat satu sama lain.

**contoh menghitung Algoritma PageRank** 

$$r_j=\sum_{i \rightarrow j} \frac{r_i}{d_i}$$

* $r_{j}$ : nilai rangking dari node j yang dihitung  
* $\sum_{i \rightarrow j}$ : jumlah dari semua node 𝑖 yang memiliki tautan (link) menuju node 𝑗.
* $r_{i}$ : nilai rangking dari node 𝑖 yang memberikan tautan ke node 𝑗.  
* $d_{i}$ : derajat keluar (out-degree) dari node 𝑖 yaitu jumlah tautan yang keluar dari node 𝑖.  

Dengan rumus diatas maka dapat menulis sistem linier :  

$r0 = \frac{r4}{3}$  
$r1 = \frac{r2}{2} + \frac{r4}{3} + r3$  
$r2 = \frac{r0}{3} + \frac{r4}{3}$  
$r3 = \frac{r2}{2} + \frac{r0}{3}$  
$r4 = \frac{r0}{3} + r1$  

maka didapat matriks dari persamaan diatas :  
$$
A =\left(\begin{array}{ccccc}
0 & 0 & 0 & 0 & \frac{1}{3} \\
0 & 0 & \frac{1}{2} & 1 & \frac{1}{3} \\
\frac{1}{3} & 0 & 0 & 0 & \frac{1}{3} \\
\frac{1}{3} & 0 & \frac{1}{2} & 0 & 0 \\
\frac{1}{3} & 1 & 0 & 0 & 0
\end{array}\right)
$$  
$$
V0 = \begin{equation*}
\begin{bmatrix}
0.2\\
0.2\\
0.2\\
0.2\\
0.2
\end{bmatrix}
\end{equation*}
$$  



## Menghitung Menggunakan cara manual

In [1]:
import numpy as np
A = np.array([[0,0,0,0,1/3], [0,0,1/2,1,1/3], [1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
V0 = np.array([[0.2], [0.2], [0.2], [0.2], [0.2]])

V1 = A @ V0

print(V1)

[[0.06666667]
 [0.36666667]
 [0.13333333]
 [0.16666667]
 [0.26666667]]


In [2]:
V2 = A @ V1
print(V2)

[[0.08888889]
 [0.32222222]
 [0.11111111]
 [0.08888889]
 [0.38888889]]


In [3]:
V3 = A @ V2
print(V3)

[[0.12962963]
 [0.27407407]
 [0.15925926]
 [0.08518519]
 [0.35185185]]


In [4]:
V4 = A @ V3
print(V4)

[[0.11728395]
 [0.28209877]
 [0.16049383]
 [0.12283951]
 [0.31728395]]


In [5]:
V5= A @ V4
print(V5)

[[0.10576132]
 [0.30884774]
 [0.14485597]
 [0.11934156]
 [0.32119342]]


In [7]:
#|V(i+1)-Vi|**2 < toleransi (0,01)
a = (0.10576132 - 0.11728395)**2
b = (0.30884774 - 0.28209877)**2
c = (0.14485597 - 0.16049383)**2
d = (0.11934156 - 0.12283951)**2
e = (0.32119342 - 0.31728395)**2

f = a+b+c+d+e

print(f)

0.0011203406734407993


Penjelasan :

- hasil dari $|V_{i+1}-V_{i}|^{2}$ yaitu 0.007681756318244199 < 0,01 .

- jadi urutan rangking dari page diatas dari yang paling tinggi adalah r5, r2, r3, r1, r4

## Menghitung menggunakan cara perualangan

In [1]:
import numpy as np

# data seperti di contoh di atas
A = np.array([[0,0,0,0,1/3], [0,0,1/2,1,1/3], [1/3,0,0,0,1/3],[1/3,0,1/2,0,0],[1/3,1,0,0,0]])
Av0 = np.array([[0.2], [0.2], [0.2], [0.2], [0.2]])


def kaliMatrik(A, vlama):
  # mengkalikan matrix dengan vlama
  v = A@vlama
  return v

def convergen(vlama, v, toleransi):
    # menghitung selisih antara vbaru dan vlama
    selisih = v - vlama
    # menghitung nilai convergen nya
    convergen = 0
    for i in selisih:
      convergen += i[0]**2
    # mengembalikan true jika convergen kurang dari nilai toleransi jika tidak false
    return convergen < toleransi

def sort(numpy_arr):
  # sorting data ranking menggunakan algoritma bubble sort
  sorted = False
  i = 0
  rank = []
  data = []
  iter = 1
  for k in numpy_arr:
    data.append(k[0])
    rank.append(iter)
    iter += 1
  
  
  while sorted == False and i < len(data):
    isSwap = False
    for j in range(len(data) - 1 - i):
      if data[j] < data[j + 1]:
        rank[j], rank[j + 1] = rank[j + 1], rank[j]
        data[j], data[j + 1] = data[j + 1], data[j]
        isSwap = True

    if isSwap == False:
      sorted = True
    i += 1
  return rank


# melakukan ranking 
def ranking(v, A, toleransi):
    vlama = v
    coverage = False
    perulangan = 0
    # jika coverage true perulangan berhenti
    while not coverage:
        # mencari vbaru
        vbaru = kaliMatrik(A, vlama)
        # mencari selisih dan membadingkan nya dengan nilai toleransi 
        # jika nilai convergen lebih kecil dari nilai toleransi mengubah coverage menjadi True
        coverage = convergen(vlama, vbaru, toleransi)
        vlama = vbaru
        perulangan += 1
    
    # mengembalikan jumlah looping dan v terakhir
    return (vbaru, perulangan)

# data yang sama seperti contoh di atas
print("Data yang sama dengan contoh di atas")
ranking1 = ranking(Av0, A, 0.01)
print("jumlah perulangan: ", ranking1[1])
print("ranking data: \n", ranking1[0])
print("ranking: ", sort(ranking1[0]))
print()

Data yang sama dengan contoh di atas
jumlah perulangan:  3
ranking data: 
 [[0.12962963]
 [0.27407407]
 [0.15925926]
 [0.08518519]
 [0.35185185]]
ranking:  [5, 2, 3, 1, 4]

